language: node_js
node_js:
    - "10"
before_deploy:
    - npm run deploy
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    local-dir: docs
    on:
        branch: master
